// Code generated by mockery v2.43.0. DO NOT EDIT.

package cloudinary

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCloudinaryService is an autogenerated mock type for the CloudinaryService type
type MockCloudinaryService struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, input
func (_m *MockCloudinaryService) UploadImage(ctx context.Context, input interface{}) (string, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (string, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCloudinaryService creates a new instance of MockCloudinaryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudinaryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudinaryService {
	mock := &MockCloudinaryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
