// Code generated by mockery v2.43.0. DO NOT EDIT.

package repositories

import (
	context "context"

	entities "github.com/satryanararya/go-chefbot/entities"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRatingReviewRepository is an autogenerated mock type for the RatingReviewRepository type
type MockRatingReviewRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, ratingReview
func (_m *MockRatingReviewRepository) Create(ctx context.Context, ratingReview *entities.RatingReview) error {
	ret := _m.Called(ctx, ratingReview)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.RatingReview) error); ok {
		r0 = rf(ctx, ratingReview)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRatingReviewRepository) Delete(ctx context.Context, userID uuid.UUID, recipeID int64) error {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) error); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRatingReviewRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]entities.RatingReview, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entities.RatingReview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entities.RatingReview, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entities.RatingReview); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.RatingReview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRatingReviewRepository creates a new instance of MockRatingReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRatingReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRatingReviewRepository {
	mock := &MockRatingReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
