name: Development CI/CD

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Linting Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Golang Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  build-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Run usecase coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./usecases
      - name: Build image
        run: docker build -t go-chefbot .